### ISSUE TITLE
eslint-plugin-import unmet peer dependency 

### ISSUE THREAD

**Issue by rayrutjes** [algolia/eslint-config-algolia#37]
The `eslint-plugin-import` lib does not currently support eslint 4.
We will need to update once this is merged: https://github.com/benmosher/eslint-plugin-import/pull/871

**Comment by vvo** [comment]
It is supported but there's a warning for now yes.

**Comment by vvo** [comment]
But it works

**Comment by rayrutjes** [comment]
I tried to add https://github.com/vuejs/eslint-plugin-vue to have better warnings for .vue files, but I found no way to make it work in the current config.

```
yarn lint                                   ⏎ ✹
yarn lint v0.24.6
$ eslint --ext .js,.vue .
Cannot read property 'some' of undefined
TypeError: Cannot read property 'some' of undefined
    at Object.isUnambiguousModule [as isModule] (/Users/raymond/Code/vue-instantsearch/node_modules/eslint-module-utils/unambiguous.js:29:18)
    at Function.ExportMap.parse (/Users/raymond/Code/vue-instantsearch/node_modules/eslint-plugin-import/lib/ExportMap.js:348:20)
    at Function.ExportMap.for (/Users/raymond/Code/vue-instantsearch/node_modules/eslint-plugin-import/lib/ExportMap.js:326:25)
    at Function.ExportMap.get (/Users/raymond/Code/vue-instantsearch/node_modules/eslint-plugin-import/lib/ExportMap.js:284:23)
    at processBodyStatement (/Users/raymond/Code/vue-instantsearch/node_modules/eslint-plugin-import/lib/rules/namespace.js:58:47)
    at Array.forEach (native)
    at Linter.Program (/Users/raymond/Code/vue-instantsearch/node_modules/eslint-plugin-import/lib/rules/namespace.js:87:14)
    at emitOne (events.js:101:20)
    at Linter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/Users/raymond/Code/vue-instantsearch/node_modules/eslint/lib/util/node-event-generator.js:265:26)
error Command failed with exit code 1.
```

**Comment by vvo** [comment]
This is something different, see the issue on vue rslint plugin and also the readme here explains it

**Comment by rayrutjes** [comment]
I think you forgot the link ;)

**Comment by vvo** [comment]
https://github.com/vuejs/eslint-plugin-vue/issues/21#issuecomment-308957697

Also they just fixed the vue template plugin so that import plugin works alongside, import plugin might still say it's not compatible with latest eslint but it is.

**Comment by vvo** [comment]
(this warning is not an issue right now)
